name: jax-fem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - libblas
  - liblapack
  - pip:
      - fenics-basix>=0.10.0
      - gmsh==4.14.0
      - jax==0.8.0
      - jax-fem==0.0.11
      - jaxlib==0.8.0
      - ml-dtypes==0.5.4
      - opt-einsum==3.4.0
      - pyfiglet==1.0.3
      - setuptools==80.9.0
      - wheel==0.45.1
      - torch==2.11.0
      - einops
      - jaxtyping
      - pydantic==2.13.2
      - h5py==3.16.0
      - tqdm==4.67.3
