name: jax-fem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fenics
  - h5py
  - hdf5
  - loguru
  - matplotlib
  - meshio
  - mpi4py
  - mpmath
  - mumps-mpi
  - netcdf4
  - numpy
  - openmpi
  - packaging
  - petsc
  - petsc4py
  - pillow
  - pkgconfig
  - platformdirs
  - pooch
  - pybind11
  - pygments
  - pyvista
  - pyyaml
  - requests
  - rich
  - scalapack
  - scipy
  - scooby
  - six
  - slepc
  - slepc4py
  - sympy
  - pip
  - pip:
      - fenics-basix==0.9.0
      - gmsh==4.14.0
      - jax==0.6.2
      - jax-fem==0.0.11
      - ml-dtypes==0.5.4
      - opt-einsum==3.4.0
      - pyfiglet==1.0.3
      - setuptools==80.9.0
      - wheel==0.45.1
